# kafka.yaml
# ------------------
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      compression.type: lz4
      log.cleanup.policy: delete
      inter.broker.protocol.version: '3.9'
      offsets.retention.minutes: 10080
      log.retention.hours: 168
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    replicas: 1
    resources:
      limits:
        cpu: 2
        memory: 3Gi
      requests:
        cpu: 1
        memory: 2Gi
    storage:
      size: 10Gi
      type: persistent-claim
      class: longhorn
    version: 3.9.1
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*

  zookeeper:
    replicas: 1
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    storage:
      size: 1Gi
      type: persistent-claim
      class: longhorn