apiVersion: v1
kind: Service
metadata:
  name: clickhouse-nodeport
  namespace: clickhouse
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      nodePort: 30123
      protocol: TCP
